version: '3.1'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend:prod
    secrets:
      - db_password
    environment:
      - MONGO_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

secrets:
  db_password:
    file: ./db_password.txt
